services:
  laravel-docker:
    container_name: laravel-docker
    build: .
    command: php artisan serve --host=0.0.0.0 --port=8080
    volumes:
      - ./laravel-app:/var/www/html
      - ./laravel-app/vendor:/var/www/html/vendor
    ports:
      - 8080:8080
    networks:
      - invoice-be
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: tu
      MYSQL_DATABASE: invoice-builder
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    networks:
      - invoice-be

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:db
      - PMA_USER:tu
      - PMA_PASSWORD:123456
    depends_on:
      - db
    networks:
      - invoice-be

networks:
  invoice-be:
    driver: bridge
